source 'https://rubygems.org'

gem 'csv'
gem 'observer'

group :jekyll_plugins do
    gem 'activesupport'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-regex-replace'
    gem 'jekyll-tabs'
    gem 'jekyll-toc'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jekyll-sitemap'
    gem 'jemoji'
    gem 'feedjira'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'httparty'
    gem 'css_parser'

end